### ISSUE TITLE
One question about the CCVR.ipynb

### ISSUE THREAD

**Issue by Bhongcheng** [dadodimauro/MLDL-Federated-Learning#1]
Thanks for your code. I have one question about the code. Could you please help me?

![image](https://user-images.githubusercontent.com/90205287/216541794-a15e4f04-5283-41ca-a1fa-b65271a9175f.png)
Why we need this code? I think the value of "fd_d" is aleardy feature we need, why should we push it to relu and np.power?

Thank you

**Comment by dadodimauro** [comment]
In the paper https://arxiv.org/pdf/2106.05001.pdf they say at page 8 about the implementation, that they applied a ReLU and Tukey’s transformation to make it more “Gaussian”

**Comment by Bhongcheng** [comment]
Really thank you for your reply. (My English is a little poor, and I don't know how to express my gratitude)
